version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: smart_farm_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin@2026
      POSTGRES_DB: farm_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    container_name: smart_farm_api_img
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
volumes:
  postgres_data: